# Generated by Django 5.0.1 on 2024-01-15 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_add_realtor_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('preview_image', models.ImageField(upload_to='images/')),
                ('description', models.TextField()),
                ('area', models.IntegerField(db_index=True)),
                ('rooms_no', models.IntegerField(db_index=True)),
                ('price_month', models.IntegerField(db_index=True)),
                ('currency', models.CharField(choices=[('EUR', 'EUR'), ('USD', 'USD')], default='EUR', max_length=3)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_added',),
                'index_together': {('area', 'rooms_no', 'price_month', 'price_month', 'currency')},
            },
        ),
    ]
